SiteTracker/WebsiteRoutes/routes.py
from flask import redirect, render_template, request, make_response, flash, url_for
from datetime import datetime, timedelta
import status
from flask_jwt_extended import jwt_required, get_jwt_identity
from SiteTracker.WebsiteRoutes.websites_util import fetch_website_id, get_notify_status, get_user_urls, toggle_notify_status, update_website_user_map, save_website, savedata_website_user_map, check_userid_websiteid_relation, get_user_website_relation_status, set_user_website_relation_status
from SiteTracker.WebsiteRoutes.analyse_data import get_website_weekly_performance
from SiteTracker.forms import AddWebsiteForm
from flask import Blueprint
website=Blueprint("website",__name__,static_folder="static",template_folder="templates")
'''
--> Needs jwt token
--> Checks if the website already exists in the website table
--> Adds the site if exists if not returns error 409
--> Adds data to the user_map_id table 
'''
@website.route('/add',methods=['POST','GET'])
def add_website():
    form=AddWebsiteForm()
    if request.method=='POST':
        try:
            url_value=request.form.get('url')
            create_datetime_value=datetime.now()
            update_datetime_value=datetime.now()
            role_value=request.form.get('role') if request.form.get('role') else 1
            isactive_value=True
            do_notify_value=request.form.get('role') if (request.form.get('role') and request.form.get('role')=='YES') else 1
            @jwt_required()
            def function_test():
                current_user_id=get_jwt_identity()
                website_id=fetch_website_id(url_value)
                if website_id is None:
                    response=save_website(url_value,create_datetime_value,update_datetime_value,isactive_value)
                    if response:
                        fetched_website_id=fetch_website_id(url_value)
                        another_response=savedata_website_user_map(fetched_website_id,current_user_id,role_value,create_datetime_value,update_datetime_value,isactive_value,do_notify_value)
                        if another_response:
                            msg='website added'
                            return True,msg
                else:
                    relation_exist=check_userid_websiteid_relation(current_user_id,website_id)
                    is_active=get_user_website_relation_status(current_user_id,website_id)
                    if(relation_exist and is_active):
                        msg='Website already in to monitor list'
                        return False,msg
                    elif(relation_exist and not is_active):
                        res=set_user_website_relation_status(current_user_id,website_id,True)
                        if res:
                            msg='The relation found in database, changed to active from unactive'
                            return True,msg
                    else:
                        response1=savedata_website_user_map(website_id,current_user_id,role_value,create_datetime_value,update_datetime_value,isactive_value,do_notify_value)
                        if response1:
                            msg='website added to map table'
                            return True,msg
            #calling the function
            response,msg=function_test()
            if response:
                flash(msg,'success')
                return redirect(url_for('website.fetch_websites'))
                # return make_response({'msg':msg},status.HTTP_201_CREATED)
            else:
                raise Exception(msg)
                # return make_response({'error':msg},status.HTTP_400_BAD_REQUEST)
        except Exception as ex:
            flash(str(ex),'danger')
            return redirect(url_for('website.add_website'))
            # return make_response({'error':str(ex)},status.HTTP_400_BAD_REQUEST)
    elif request.method=='GET':
        return render_template('add-website.html',form=form)

'''
--> API to update/change the website registered to the user to monitor
--> If the new website doesn't exists in the database, it add it in website_table and updates the user_map_table
--> if the website exists in database , it simly updates the user_map_table 
'''
@website.route('/update/<int:website_id>',methods=['POST','PUT','GET'])
def update_website(website_id):
    if request.method in['PUT','POST']:
        update_url=request.form['url']
        @jwt_required()
        def jwtfunction():
            try:
                current_user_id=get_jwt_identity()
                update_url_id=fetch_website_id(update_url)

                #condition to add url to database if it doesn't exists already
                if update_url_id is None:
                    save_website(update_url,datetime.utcnow(),datetime.utcnow(),True)
                    update_url_id=fetch_website_id(update_url)
                    print(f'--> Added "{update_url}" to database with id: {update_url_id}')
                else:
                    relation_exist=check_userid_websiteid_relation(current_user_id,update_url_id)
                    is_active=get_user_website_relation_status(current_user_id,update_url_id)
                    # print(relation_exist,is_active)
                    if(relation_exist and is_active):
                        msg='Website already in monitor list'
                        return False,msg
                    elif(relation_exist and not is_active):
                        res=set_user_website_relation_status(current_user_id,update_url_id,True)
                        if res:
                            msg='The relation found in database, changed to active from unactive'
                            return True,msg
                
                # update_res=update_website_user_map(update_url_id,current_user_id,website_id)
                update_res=1
                if update_res:
                    return True,'Website changed/updated'
            except Exception as ex:
                return False,str(ex)
        resp,msg=jwtfunction()
        if resp:
            flash(msg,'success')
            return redirect(url_for('website.fetch_websites'))
            # return make_response({'message':msg},status.HTTP_200_OK)
        else:
            flash(msg,'warning')
            return redirect(url_for('website.fetch_websites'))
            # return make_response({'error':msg},status.HTTP_400_BAD_REQUEST)
    if request.method in['GET']:
        form=AddWebsiteForm()
        return render_template('add-website.html',page_name='Update Site',form=form,website_id=website_id)

'''
--> Api to remove the website from the users monitoring list(set relation to inactive)
'''
@website.route('/remove/<int:website_id>',methods=['DELETE','GET'])
@jwt_required()
def remove_website(website_id):
    if request.method=='GET' or request.method=='DELETE':
        try:
            current_user_id=get_jwt_identity()
            relation_exist=check_userid_websiteid_relation(current_user_id,website_id)
            is_active=get_user_website_relation_status(current_user_id,website_id)
            if not relation_exist:
                return make_response({'error':'No such entry exists'},status.HTTP_404_NOT_FOUND)
            if set_user_website_relation_status(current_user_id,website_id,status=False):
                flash('Site successfuly removed','success')
                return redirect(url_for('website.fetch_websites'))
                # return make_response({'Message':'Website removed successfully from your list'})
        except Exception as ex:
            flash(ex,'danger')
            return redirect(url_for('website.fetch_websites'))
            # return make_response({'error':str(ex)},status.HTTP_400_BAD_REQUEST)

@website.route('/all',methods=['GET'])
@jwt_required() #check pending :isactive functionality
def fetch_websites():
    if request.method=='GET':
        try:
            current_user_id=get_jwt_identity()
            datafetched=get_user_urls(current_user_id)
            # print(datafetched)
            res=make_response(render_template('dashboard.html',url_data_list=datafetched))
            return res
            # return make_response({'msg':'data fetched successfully','url_list':datafetched},status.HTTP_200_OK)
        except Exception as ex:
            flash(ex,'danger')
            res= redirect(url_for('website.fetch_websites'))
            return res
            # return make_response({'error':str(ex)},status.HTTP_400_BAD_REQUEST)
    else:
        return make_response({'error':'This method is not supported'},status.HTTP_405_METHOD_NOT_ALLOWED)

@website.route('/<int:website_id>',methods=['GET'])
@jwt_required()
def get_site_report(website_id):
    if request.method=='GET':
        try:
            current_user_id=get_jwt_identity()
            rel=check_userid_websiteid_relation(current_user_id,website_id)
            if rel:
                weekly_report_data=get_website_weekly_performance(website_id)
                if(len(weekly_report_data)==0):
                    flash('No data available for the site yet','warning')
                    return redirect(url_for('website.fetch_websites'))
                return render_template('website-data.html',data_list=weekly_report_data,website_id=website_id)
                # return make_response(weekly_report_data,status.HTTP_200_OK)
            else:
                raise Exception("subscription to the website doesn't exist")
                # return make_response({'error':"subscription to the website doesn't exist"},status.HTTP_400_BAD_REQUEST)
        except Exception as ex:
            flash(ex,'danger')
            return redirect(url_for('website.get_site_report',website_id=website_id))
            # return make_response({'error':str(ex)},status.HTTP_400_BAD_REQUEST)


@website.route('/data/<int:website_id>',methods=['GET'])
@jwt_required()
def site_data(website_id):
    if request.method=='GET':
        try:
            current_user_id=get_jwt_identity()

SiteTracker/templates/about.html
{% extends "index.html" %}    
{% block index %}
    <h1>About page</h1>
{% endblock index %}

SiteTracker/templates/add-website.html
{% extends "index.html" %}
{% block index %}
<!-- Header -->
<header id="header" class="ex-header">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                {% if page_name %}
                <h1>Update Site</h1>
                {% else %}
                <h1>Add Site</h1>
                {% endif %}
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
<!-- end of header -->
<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Please Enter Data</h4>
            {% if page_name %}
            <form class="forms-sample" method="POST" action="{{url_for('website.update_website',website_id=website_id)}}">
            {% else %}
            <form class="forms-sample" method="POST" action="{{url_for('website.add_website')}}">
            {% endif %}
            
                {{ form.hidden_tag() }}
                
                <div class="form-group row">
                    {{form.url.label(class="col-sm-3 col-form-label")}}
                    <div class="col-sm-9">
                        {% if form.url.errors %}
                        {{ form.url(class="form-control form-control-lg is-invalid")}}
                            <div class="invalid-feedback">
                                {% for error in form.url.errors %}
                                    <span>{{error}}</span>
                                {% endfor %}
                            </div>
                        {% else %}
                            {{ form.url(class="form-control form-control-lg")}}
                        {% endif %}
                    </div>
                </div>

                {% if not page_name %}
                    <div class="form-group row">
                        {{form.role.label(class="col-sm-3 col-form-label")}}
                        
                        <div class="col-sm-4">
                            <div class="form-check">
                                {{form.role(class="form-check-input")}}
                                    <i class="input-helper"></i>
                            </div>
                        </div>
                    </div>
                    
                    <div class="form-group row">
                        {{form.notify.label(class="col-sm-3 col-form-label")}}
                        
                        <div class="col-sm-4">
                            <div class="form-check">
                                {{form.notify(class="form-check-input")}}
                                    <i class="input-helper"></i>
                            </div>
                        </div>
                    </div>
                {% endif %}
                
                <div class="form-group">
                    {{form.submit(class='btn btn-primary me-2')}}
                    <button class="btn btn-light">Cancel</button>
                </div>
            </form>
        </div>
    </div>
</div>
{% endblock index %}

SiteTracker/templates/dashboard.html
{% extends "index.html" %}
{% block index %}
<!-- Header -->
<header id="header" class="ex-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Monitored Sites</h1>
      </div> <!-- end of col -->
    </div> <!-- end of row -->
  </div> <!-- end of container -->
</header> <!-- end of ex-header -->
<!-- end of header -->
<div class="ex-basic-2">
  <div class="container">
    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>
                ID
              </th>
              <th>
                URL
              </th>
              <th>
                Status
              </th>
              <th>
                Role
              </th>
              <th>
                Notify
              </th>
            </tr>
          </thead>
          <tbody>
            {% for url in url_data_list %}
            <tr>
              <td>
                {{url.id}}
              </td>
              <td>
                <a href="{{url_for('website.get_site_report',website_id=url.id)}}">{{url.url}}</a>
                <span><a class="badge badge-primary" style="float: right;" href="{{url_for('website.update_website',website_id=url.id)}}">Update</a></span>
              </td>
              <td>
                {% if url.active %}
                <label class="badge badge-success">Active</label>
                {% else %}
                <label class="badge badge-danger">Inactive</label>
                {% endif %}
                <!-- <div class="progress">
            <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div> -->
              </td>
              <td>
                {{url.role}}
              </td>
              <td>
                {{url.notify}}
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
        <a href="{{url_for('website.add_website')}}">Add website</a>
      </div>
    </div> <!-- end of row -->
  </div> <!-- end of container -->
</div> <!-- end of ex-basic -->
<!-- end of terms content -->
{% endblock index %}

SiteTracker/templates/forgot_password.html
{% extends "index.html" %}
{% block index %}

<!-- Header -->
<header id="header" class="ex-2-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Forgot Password</h1>
                <p><a class="white" href="{{url_for('log_in')}}">Back to login?</a></p>
                <!-- Sign Up Form -->
                <div class="form-container">
                    <form id="logInForm" data-toggle="validator" data-focus="false" method="POST"
                        action="{{url_for('forgot_password')}}">
                        <div class="form-group">
                            <input type="email" class="form-control-input" name="email" id="femail" required>
                            <label class="label-control" for="femail">Registered Email</label>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="form-control-submit-button">Submit</button>
                        </div>
                        <div class="form-message">
                            <div id="lmsgSubmit" class="h3 text-center hidden"></div>
                        </div>
                    </form>
                </div> <!-- end of form container -->
                <!-- end of sign up form -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
{% endblock index %}

SiteTracker/templates/log-in.html
{% extends "index.html" %}    
{% block index %}
    <!-- Header -->
    <header id="header" class="ex-2-header">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <h1>Log In</h1>
                   <p>Don't have an account? Then please <a class="white" href="{{url_for('sign_up')}}">Sign Up</a></p> 
                    <!-- Sign Up Form -->
                    <div class="form-container">
                        <form id="logInForm" data-toggle="validator" data-focus="false" method="POST" action="{{url_for('log_in')}}">
                            <div class="form-group">
                                <input type="email" class="form-control-input" name="email" id="lemail" required>
                                <label class="label-control" for="lemail">Email</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <input type="password" class="form-control-input" name="password" id="lpassword" required>
                                <label class="label-control"  for="lpassword">Password</label>
                                <div class="help-block with-errors"></div>
                            </div>
                            <div class="form-group">
                                <button type="submit" class="form-control-submit-button">LOG IN</button>
                            </div>
                            <div class="form-message">
                                <div id="lmsgSubmit" class="h3 text-center hidden"></div>
                            </div>
                        </form>
                    </div> <!-- end of form container -->
                    <!-- end of sign up form -->
                    <p>Forgot Password? 
                        <small class="text-muted">
                            <a class="white" href="{{url_for('forgot_password')}}">Click here</a>
                        </small>
                    </p> 
                </div> <!-- end of col -->
            </div> <!-- end of row -->
        </div> <!-- end of container -->
    </header> <!-- end of ex-header -->
    <!-- end of header -->
{% endblock index %}

SiteTracker/templates/reset_password.html
{% extends "index.html" %}
{% block index %}

<!-- Header -->
<header id="header" class="ex-2-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Reset Password</h1>
                <!-- Sign Up Form -->
                <div class="form-container">
                    <form id="logInForm" data-toggle="validator" data-focus="false" method="POST">
                        <div class="form-group">
                            <input type="password" class="form-control-input" name="password" required>
                            <label class="label-control" for="femail">New Password</label>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <input type="password" class="form-control-input" name="confirm_password" 
                                required>
                            <label class="label-control" for="femail">Confirm Password</label>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="form-control-submit-button">Submit</button>
                        </div>
                        <div class="form-message">
                            <div id="lmsgSubmit" class="h3 text-center hidden"></div>
                        </div>
                    </form>
                </div> <!-- end of form container -->
                <!-- end of sign up form -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
{% endblock index %}

SiteTracker/templates/sign-up.html
{% extends "index.html" %}
{% block index %}

<!-- Header -->
<header id="header" class="ex-2-header">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h1>Sign Up</h1>
                <p>Fill out the form below to sign up for Tivo. Already signed up? Then just <a class="white"
                        href="{{url_for('log_in')}}">Log In</a></p>
                <!-- Sign Up Form -->
                <div class="form-container">
                    <form id="signUpForm" data-toggle="validator" data-focus="false" method="POST"
                        action="{{url_for('sign_up')}}">
                        <div class="form-group">
                            <input type="email" name="email" class="form-control-input" id="semail" required>
                            <label class="label-control" for="semail">Email</label>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <input type="text" name="username" class="form-control-input" id="sname" required>
                            <label class="label-control" for="sname">Name</label>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <input type="text" name="password" class="form-control-input" id="spassword" required>
                            <label class="label-control" for="spassword">Password</label>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group checkbox">
                            <input type="checkbox" id="sterms" value="Agreed-to-Terms" required>I agree with Tivo's <a
                                href="privacy-policy.html">Privacy Policy</a> and <a href="terms-conditions.html">Terms
                                Conditions</a>
                            <div class="help-block with-errors"></div>
                        </div>
                        <div class="form-group">
                            <button type="submit" class="form-control-submit-button">SIGN UP</button>
                        </div>
                        <div class="form-message">
                            <div id="smsgSubmit" class="h3 text-center hidden"></div>
                        </div>
                    </form>
                </div> <!-- end of form container -->
                <!-- end of sign up form -->
            </div> <!-- end of col -->
        </div> <!-- end of row -->
    </div> <!-- end of container -->
</header> <!-- end of ex-header -->
{% endblock index %}

SiteTracker/templates/website-data.html
{% extends "index.html" %}
{% block index %}
<!-- Header -->
<header id="header" class="ex-header">
  <div class="container">
    <div class="row">
      <div class="col-md-12">
        <h1>Site Performance</h1>
      </div> <!-- end of col -->
    </div> <!-- end of row -->
  </div> <!-- end of container -->
</header> <!-- end of ex-header -->
<!-- end of header -->
<div class="ex-basic-2">
  <div class="container">

    <!-- Canvas to draw chart -->
    <canvas id="myChart" width="1000" height="300" style="max-width: 500;max-height:500;"></canvas>
    <!-- Canvas Ends -->

    <div class="row">
      <div class="table-responsive">
        <table class="table table-striped">
          <thead>
            <tr>
              <th>
                Date
              </th>
              <th>
                Average Response Time / Day
              </th>
              <th>
                Status
              </th>
            </tr>
          </thead>
          <tbody>
            {% for data in data_list %}
            <tr>
              <td>
                {{data.date}}
              </td>
              <td>
                {{data.average_response_time}}
              </td>
              <td>
                {{data.status}}
                <!-- <div class="progress">
            <div class="progress-bar bg-success" role="progressbar" style="width: 25%" aria-valuenow="25" aria-valuemin="0" aria-valuemax="100"></div>
          </div> -->
              </td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div> <!-- end of row -->

    <div class="row d-flex justify-content-center">
      <a type="button" class="btn btn-success btn-icon-text"
        href="{{url_for('website.update_website',website_id=website_id)}}">
        <i class="ti-alert btn-icon-prepend"></i>
        Update
      </a>
      <button type="button" class="btn btn-primary btn-icon-text" onclick="change_notification()" id="notification_status">
        Enable Notifications
        <i class="ti-file btn-icon-append"></i>
      </button>
      <a type="button" class="btn btn-danger btn-icon-text"
        href="{{url_for('website.remove_website',website_id=website_id)}}">
        <i class="ti-alert btn-icon-prepend"></i>
        Remove
      </a>
    </div>
  </div> <!-- end of container -->
</div> <!-- end of ex-basic -->
<!-- end of terms content -->

<script 
  src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.8.0/chart.min.js" 
  integrity="sha512-sW/w8s4RWTdFFSduOTGtk4isV1+190E/GghVffMA9XczdJ2MDzSzLEubKAs5h0wzgSJOQTRYyaz73L3d6RtJSg==" 
  crossorigin="anonymous" 
  referrerpolicy="no-referrer">
</script>

<script>

  var dates=[]
  var avg_res_time=[]
  var common_res_status=[]

  async function get_data(){

    const fetched_data= await fetch('/website/data/{{website_id}}')
    let data=await fetched_data.json()
    var weekly_data=data['weekly_data']
    // console.log(weekly_data)
    for(let i=0;i<weekly_data.length;i++){
      dates.push(weekly_data[i]['date']);
      avg_res_time.push(weekly_data[i]['average_response_time']);
      common_res_status.push(weekly_data[i]['status']);
    }
    create_graph()
  }
  
  function create_graph(){
    const ctx = document.getElementById('myChart');
    const myChart = new Chart(ctx, {
    type: 'bar',
    data: {
        labels: dates,
        datasets: [{
            label: 'Average response time',
            data: avg_res_time,
            backgroundColor: [
                'rgba(255, 99, 132, 0.2)',
                'rgba(54, 162, 235, 0.2)',
                'rgba(255, 206, 86, 0.2)',
                'rgba(75, 192, 192, 0.2)',
                'rgba(153, 102, 255, 0.2)',
                'rgba(255, 159, 64, 0.2)'
            ],
            borderColor: [
                'rgba(255, 99, 132, 1)',
                'rgba(54, 162, 235, 1)',
                'rgba(255, 206, 86, 1)',
                'rgba(75, 192, 192, 1)',
                'rgba(153, 102, 255, 1)',
                'rgba(255, 159, 64, 1)'
            ],
            borderWidth: 1
        }]
    },
    options: {
        responsive: false,
        legend: {
            position: 'top',
        },
        title: {
            display: true,
            text: 'Site Data'
        },
        scales: {
            y: {
                beginAtZero: true,
                title: {
                  display: true,
                  text: 'Seconds'
                }
            },
            x: {
                title: {
                  display: true,
                  text: 'Date'
                }
            }
        }
    }
    });
  }

  function change_button(notify){
    let ele=document.getElementById('notification_status');
    if(notify){
      ele.innerHTML='Disable Notifications'
      ele.className='btn btn-warning btn-icon-text'
    }
    else{
      ele.innerHTML='Enable Notifications'
      ele.className='btn btn-primary btn-icon-text'
    }
  }

  async function change_notification(){
    notify_status=await send_notification_req('POST')
    change_button(notify_status)
  }

  async function send_notification_req(methd){
    const fetched_data=await fetch('/website/notification/{{website_id}}',{method:methd})
    let data=await fetched_data.json()
    return data['notify_status']
  }

  get_data()
</script>
{% endblock index %}